### ISSUE TITLE
How to access data submitted via “multipart/form-data” from the server side?

### ISSUE THREAD

**Issue by ChenyaZhang** [expressjs/node-multiparty#146]
In the front-end, I try to upload photos (Objective c)

In the back-end, I try to get all image data and store them in database (Node.js, Multiparty for http, later Mongodb, Mongoose for database):
`var multiparty = require('multiparty');
var http = require('http');
var util = require('util');

http.createServer(function(req, res) {

    if (req.url === '/upload' && req.method === 'POST') {
        // parse a file upload
        var count = 0;
        var form = new multiparty.Form();

        console.dir(req.body);

        // Errors may be emitted 
        // Note that if you are listening to 'part' events, the same error may be 
        // emitted from the `form` and the `part`. 
        form.on('error', function(err) {
            console.log('Error parsing form: ' + err.stack);
        });

        form.on('file', function(err, files) {
            console.log('files: %@', files);
            count++;
        });

        // Close emitted after form parsed 
        form.on('close', function() {
            console.log('Upload completed!');
            // res.setHeader('text/plain');
            // res.end('Received ' + count + ' files');
            console.log('Received ' + count + ' files');
        });

        form.parse(req, function(err, fields, files) {
            res.writeHead(200, {'content-type': 'text/plain'});
            res.write('received upload:\n\n');
            res.end(util.inspect({fields: fields, files: files}));
            // console.log('fields: %@', fields);
            // console.log('files: %@', files);
        });
    }

}).listen(8080);`

Problem

I think I have already passed the image data to the server side, however I can only see a "path" of the image but no where to find its data.

I try to go through the "multiparty" API (https://www.npmjs.com/package/multiparty) several times but still not sure how to locate the real data.

My use case: 1) Upload photos by user 2) Go back again to the upload page to see photos uploaded previuosly by the user 3) Download all images uploaded from server by admin

**Comment by dougwilson** [comment]
Duplicate post of #145
