### ISSUE TITLE
How do I access the file contents from the "part" object?

### ISSUE THREAD

**Issue by namlet** [expressjs/node-multiparty#158]
```
if (part.filename) {
  // filename is defined when this is a file
  console.log('got file named ' + part.name);
  pdf = part;
   // ignore file's content here
   part.resume();
}
```

`pdf` is defined outside this scope and is accessible. `console.log(pdf)` produces:
```
PassThrough {
  _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: true,
     ended: true,
     endEmitted: true,
     reading: false,
     sync: false,
     needReadable: false,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: false,
  domain: null,
  _events: { end: [ [Function] ], drain: [Function], error: [Function] },
  _eventsCount: 3,
  _maxListeners: undefined,
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     needDrain: false,
     ending: true,
     ended: true,
     finished: true,
     decodeStrings: true,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: false,
     bufferProcessing: false,
     onwrite: [Function],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: true,
     errorEmitted: false,
     bufferedRequestCount: 0,
     corkedRequestsFree: CorkedRequest { next: null, entry: null, finish: [Function] } },
  writable: false,
  allowHalfOpen: true,
  _transformState:
   TransformState {
     afterTransform: [Function],
     needTransform: false,
     transforming: false,
     writecb: null,
     writechunk: null,
     writeencoding: 'buffer' },
  headers:
   { 'content-disposition': 'form-data; name="pdf"; filename="blob"',
     'content-type': 'application/pdf' },
  name: 'pdf',
  filename: 'blob',
  byteOffset: 136,
  byteCount: 340981 }
```

Here is where I'm trying to use it to write the file:
```
// Close emitted after form parsed
form.on('close', function() {
  console.log('Upload completed...sending emails');
  console.log(pdf);
  fs.writeFile("file444.pdf", pdf, 'binary', function(err) {
    console.log(err);
  });
	// sendEmails(req, res, productId, pdf);
});
```

This creates a file with the contents: `[object Object]`

Ultimately I want to email the file, but just trying to save it to disk to ease the debugging process. Where are the "contents" of the file??

**Comment by dougwilson** [comment]
The `part` object is a standard Node.js readable stream--the same object you'd get back from `fs.createReadStream` (https://nodejs.org/dist/latest-v6.x/docs/api/fs.html#fs_fs_createreadstream_path_options). You need to use `part.pipe()`, add `data` event listeners, or whatever your fancy is for interactive with ReadableStream (https://nodejs.org/dist/latest-v6.x/docs/api/stream.html#stream_class_stream_readable) objects from Node.js core.

**Comment by namlet** [comment]
When I try to do this, no events are emitted. The stream doesn't even call the "end" function.

```
var newfile = '';
    pdf.on('data', function(chunk){
      console.log(chunk);
      newfile+=chunk;
    });
    pdf.on('end', function(){
      console.log("end stream");
      console.log(newfile);
      fs.writeFile("file444.pdf", newfile, 'binary', function(err) {
        console.log(err);
      });
    });
```

I've also tried piping with identical results. zero byte file.
```var ws = fs.createWriteStream('file444.pdf');
pdf.pipe(ws);
```

**Comment by dougwilson** [comment]
@namlet can you share your full, complete code so I can run it or at least see if I can see where the issue is? Also the version of this module and the version of Node.js you are using as well as the instructions for how to call your code with a multipart request. Thanks!

**Comment by dougwilson** [comment]
I see from one of your snippets above you are trying to read the part from within the `close` event; you cannot do that, you have to read the `part` object (I assume that is what your `pdf` variable is), inside the `part` event. Getting all that information above will help me better understand what you're trying to do and help. Right now I'm just trying to guess based on very limited information provided so far.

**Comment by namlet** [comment]
Here is the calling information. The `doc` object is a jspdf object that when `doc.save()` is called the correct pdf is displayed.

```
var fd = new FormData();
var file = doc.output('blob');
fd.append('pdf', file);
$.ajax({
    url: '/email',
    type: 'POST',
    data: fd,
    success: function (data) {
        alert(data)
    },
    contentType: false,
    processData: false
});
```

Regarding what you said about the part.on event as opposed to the part.on('end'): Will the form.on('close') event be fired after the complete contents of the stream have been read?

**Comment by dougwilson** [comment]
Hi @namlet I need you to share the compete source code so I can run it. Snippets just mean I'm going to keep guessing and it's really not going to help well.

> Will the form.on('close') event be fired after the complete contents of the stream have been read?

Yes, but you have to actually read the steam, thus why you have to read it inside of the `part` event; you can't wait until the `close` event.

**Comment by namlet** [comment]
Got it, and that helped a lot. The complete source code is massive and would be difficult to extract the relevant bits. Ok, I'm getting there. Reading the stream in the part event worked well when I used the `var ws = fs.createWriteStream()` and `part.pipe(fs)`. The pdf was perfect. However, I cannot save the file to the fs, (I need to email it) and so in trying to use the syntax:

```
part.on('data', function(chunk){
  console.log(chunk);
  pdf+=chunk;
});
part.on('end', function(){
  console.log("end stream");
  // console.log(pdf);
  fs.writeFile("file444.pdf", pdf, 'binary', function(err) {
    console.log(err);
  });
});
```

This *almost* works. The file looks great except for the images are missing. I'm assuming this is because I'm just pushing it all to a string. What construct could I push this stream into that would preserve the binary aspects of it?

Thank you so much for the help!! I've spent more than a day reading all over the web and you got things mostly sorted in less than an hour!

**Comment by dougwilson** [comment]
Awesome, good to hear :) Yea, it's hard to figure this stuff out with snippets a lot of the time :) So I think the only issue with the above is that you'll wan to keep the `chunk`s as `Buffer`s. I usually just save them in an array, and then if you want one big `Buffer` at the end, just use `Buffer.concat`. Example from above adjusted:
```js
var chunks = [];
part.on('data', function(chunk){
  console.log(chunk);
  chunks.push(chunk);
});
part.on('end', function(){
  console.log("end stream");
  var pdf = Buffer.concat(chunks);
  // console.log(pdf.toString('hex'));
  fs.writeFile("file444.pdf", pdf, function(err) {
    console.log(err);
  });
});
```

**Comment by namlet** [comment]
Woohoo!!!! Thank you!! Finally got the file emailed properly!! Since you've been so helpful, one more tiny question... We also pass a field value (that I omitted to preserve clarity) and we have been unable to read the value of the passed field, but of course the name is available. Is this a stream we have to read too?

```
if (!part.filename) {
      // filename is not defined when this is a field and not a file
      console.log('got field named ', part.name);
      productId = part.value;
      part.resume();
}
```

But we always got `undefined`. Is there a special way to read this form field value as well?

**Comment by dougwilson** [comment]
So even for the field, the `part` is a ReadableStream. You'll need to do the `data` listener stuff as well. But that is probably overkill--this module can do that for you instead :) What you'll want to do is remove the `part.resume()` from your existing `part` listener (if you have one), and add a `form.on('field'` listener next to your `part` listener and in there you'll get the value already read into a string :)

**Comment by namlet** [comment]
Thanks, I think I understand. Do I remove the `part.resume()` from just the block checking for fields, or from both blocks (fields and files)? And what does that do? I assumed the `resume()` function just iterated to the next `part`. And does the `form.on('field'` listener run in parallel to the `part` listener? I guess I'm just trying to understand the lifecycle. Thanks again for all your help!

**Comment by dougwilson** [comment]
Hi @namlet basically, each `part` object needs to be read in some way. If it's a field, and you have the `field` listener, it's being read for you. Otherwise, you can call the `.resume()` method to just dump the contents. This methods is part of a standard Node.js stream: https://nodejs.org/dist/latest-v7.x/docs/api/stream.html#stream_readable_resume

Listeners run whenever the event just happens, which can be in parallel, yes.

**Comment by namlet** [comment]
Trying to grok this. Here's what I have so far, and it's almost working, but the `field` parameter in `form.on('field'` is just a string that represents the field name, not the value. What am I missing?

```
var form = new multiparty.Form(),
    pdf = '',
    productId = '';

form.on('error', function(err) {
  Log.error('Error parsing form: ' + err.stack);
});

// Parts are emitted when parsing the form
form.on('part', function(part) {
  if (part.filename) {
    var chunks = [];
    part.on('data', function(chunk){
      chunks.push(chunk);
    });
    part.on('end', function(){
      console.log("end stream");
      pdf = Buffer.concat(chunks);
    });
    part.resume();
  }

  part.on('error', function(err) {
    if (err) Log.resError(err, req, res);
  });
});

form.on('field', function(field){
  console.log("field: ", field);
});

form.on('close', function() {
  console.log('Upload completed...sending emails');
  // sendEmails(req, res, productId, pdf);
});
```

Thanks!

**Comment by namlet** [comment]
Actually, that threw an error. I'm definitely missing a resume or something.
`Error parsing form: Error: Request aborted`

**Comment by namlet** [comment]
Tried this too. Didn't throw an error, but still has `field` as field name not value.

```
var form = new multiparty.Form(),
    pdf = '',
    productId = '';

form.on('error', function(err) {
  Log.error('Error parsing form: ' + err.stack);
});

// Parts are emitted when parsing the form
form.on('part', function(part) {

  if (!part.filename) {
    part.resume();
  }

  if (part.filename) {
    var chunks = [];
    part.on('data', function(chunk){
      chunks.push(chunk);
    });
    part.on('end', function(){
      console.log("end stream");
      pdf = Buffer.concat(chunks);
    });
    part.resume();
  }

  part.on('error', function(err) {
    if (err) Log.resError(err, req, res);
  });
});

form.on('field', function(field){
  console.log("field: ", field);
});

form.on('close', function() {
  console.log('Upload completed...sending emails');
  // sendEmails(req, res, productId, pdf);
});

form.parse(req);
```

Console:
```
got file named pdf
end stream
field:  productId
Upload completed...sending emails
```

**Comment by dougwilson** [comment]
The field event is given two arguments: https://github.com/expressjs/node-multiparty#field-name-value

Example:
```js
form.on('field', function(field,value){
  console.log("field %s: %s", field, value);
});
```

**Comment by dougwilson** [comment]
In your last example, you should not have any `part.resume();` statements.

**Comment by namlet** [comment]
Any at all?

**Comment by dougwilson** [comment]
Not in your code. Basically, each `part` object needs to be read in some way. If it's a field, and you have the `field` listener, it's being read for you. Otherwise, you can call the `.resume()` method to just dump the contents. This methods is part of a standard Node.js stream: https://nodejs.org/dist/latest-v7.x/docs/api/stream.html#stream_readable_resume

You have two resumes above:

1. The first one is resuming for fields, but since you have a field listener, that is unnecessary.
2. The second one is resuming the part, but since you added a data listener, you're already reading it, so it's unnecessary.

**Comment by namlet** [comment]
AHHH! I see! Sorry, I was having a hard time wrapping my mind around that. So just in case anyone else would benefit from this, here's the final, working code:

```
var form = new multiparty.Form(),
    pdf = '',
    productId = '';

form.on('error', function(err) {
  Log.error('Error parsing form: ' + err.stack);
});

form.on('part', function(part) {

  if (part.filename) {
    var chunks = [];
    part.on('data', function(chunk){
      chunks.push(chunk);
    });
    part.on('end', function(){
      console.log("end stream");
      pdf = Buffer.concat(chunks);
    });
  }

  part.on('error', function(err) {
    if (err) Log.resError(err, req, res);
  });
});

form.on('field', function(field, value){
  if (field == 'productId') { productId = value; }
  console.log(field + ": ", value);
});

form.on('close', function() {
  console.log('Upload completed...sending emails');
  // sendEmails(req, res, productId, pdf);
});

form.parse(req);
```

Thanks again for all your help!
