### ISSUE TITLE
Option callback to specify file name

### ISSUE THREAD

**Issue by caub** [expressjs/node-multiparty#160]
Instead of always generating a random name, https://github.com/expressjs/node-multiparty/blob/master/index.js#L762, it would be interesting to have an option to upload using file.name or field.name.

This look awkward:
```js
var form = new multiparty.Form({uploadDir: dir});
form.on('file', (name, file) => {
	fs.rename(file.path, path.join(dir, name), console.error)
})
form.parse(req)
```

Something like this could be interesting:

```js
var form = new multiparty.Form({uploadDir: dir, uploadName: (name, file) => name});
form.parse(req)
```

**Comment by dougwilson** [comment]
I'm not sure why you keep opening and closing this issue, but you can find many past discussions for why this won't make it into the module.

**Comment by caub** [comment]
Hmm, yes, 

Nvm, I wasn't sure the issue was relevant, sorry if you had many notifications
